spring:
  datasource:
    url: jdbc:mysql://localhost:3306/university
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: true
logging:
  level:
    org:
      hibernate:
        SQL: debug